// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// isHeader_Value is an autogenerated mock type for the isHeader_Value type
type isHeader_Value struct {
	mock.Mock
}

// isHeader_Value provides a mock function with given fields:
func (_m *isHeader_Value) isHeader_Value() {
	_m.Called()
}

// newIsHeader_Value creates a new instance of isHeader_Value. It also registers a cleanup function to assert the mocks expectations.
func newIsHeader_Value(t testing.TB) *isHeader_Value {
	mock := &isHeader_Value{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
