// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// UnsafeReadSideManagerServiceServer is an autogenerated mock type for the UnsafeReadSideManagerServiceServer type
type UnsafeReadSideManagerServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedReadSideManagerServiceServer provides a mock function with given fields:
func (_m *UnsafeReadSideManagerServiceServer) mustEmbedUnimplementedReadSideManagerServiceServer() {
	_m.Called()
}

// NewUnsafeReadSideManagerServiceServer creates a new instance of UnsafeReadSideManagerServiceServer. It also registers a cleanup function to assert the mocks expectations.
func NewUnsafeReadSideManagerServiceServer(t testing.TB) *UnsafeReadSideManagerServiceServer {
	mock := &UnsafeReadSideManagerServiceServer{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
