// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import (
	context "context"

	chief_of_statev1 "github.com/chief-of-state/cos-go-sdk/cospb/chief_of_state/v1"

	mock "github.com/stretchr/testify/mock"
)

// ChiefOfStateServiceServer is an autogenerated mock type for the ChiefOfStateServiceServer type
type ChiefOfStateServiceServer struct {
	mock.Mock
}

// GetState provides a mock function with given fields: _a0, _a1
func (_m *ChiefOfStateServiceServer) GetState(_a0 context.Context, _a1 *chief_of_statev1.GetStateRequest) (*chief_of_statev1.GetStateResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *chief_of_statev1.GetStateResponse
	if rf, ok := ret.Get(0).(func(context.Context, *chief_of_statev1.GetStateRequest) *chief_of_statev1.GetStateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chief_of_statev1.GetStateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *chief_of_statev1.GetStateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessCommand provides a mock function with given fields: _a0, _a1
func (_m *ChiefOfStateServiceServer) ProcessCommand(_a0 context.Context, _a1 *chief_of_statev1.ProcessCommandRequest) (*chief_of_statev1.ProcessCommandResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *chief_of_statev1.ProcessCommandResponse
	if rf, ok := ret.Get(0).(func(context.Context, *chief_of_statev1.ProcessCommandRequest) *chief_of_statev1.ProcessCommandResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chief_of_statev1.ProcessCommandResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *chief_of_statev1.ProcessCommandRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewChiefOfStateServiceServerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewChiefOfStateServiceServer creates a new instance of ChiefOfStateServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChiefOfStateServiceServer(t NewChiefOfStateServiceServerT) *ChiefOfStateServiceServer {
	mock := &ChiefOfStateServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
