// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import (
	context "context"

	chief_of_statev1 "github.com/chief-of-state/cos-go-sdk/cospb/chief_of_state/v1"

	mock "github.com/stretchr/testify/mock"
)

// ReadSideHandlerServiceServer is an autogenerated mock type for the ReadSideHandlerServiceServer type
type ReadSideHandlerServiceServer struct {
	mock.Mock
}

// HandleReadSide provides a mock function with given fields: _a0, _a1
func (_m *ReadSideHandlerServiceServer) HandleReadSide(_a0 context.Context, _a1 *chief_of_statev1.HandleReadSideRequest) (*chief_of_statev1.HandleReadSideResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *chief_of_statev1.HandleReadSideResponse
	if rf, ok := ret.Get(0).(func(context.Context, *chief_of_statev1.HandleReadSideRequest) *chief_of_statev1.HandleReadSideResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chief_of_statev1.HandleReadSideResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *chief_of_statev1.HandleReadSideRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewReadSideHandlerServiceServerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewReadSideHandlerServiceServer creates a new instance of ReadSideHandlerServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReadSideHandlerServiceServer(t NewReadSideHandlerServiceServerT) *ReadSideHandlerServiceServer {
	mock := &ReadSideHandlerServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
