// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// UnsafeReadSideHandlerServiceServer is an autogenerated mock type for the UnsafeReadSideHandlerServiceServer type
type UnsafeReadSideHandlerServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedReadSideHandlerServiceServer provides a mock function with given fields:
func (_m *UnsafeReadSideHandlerServiceServer) mustEmbedUnimplementedReadSideHandlerServiceServer() {
	_m.Called()
}

// NewUnsafeReadSideHandlerServiceServer creates a new instance of UnsafeReadSideHandlerServiceServer. It also registers a cleanup function to assert the mocks expectations.
func NewUnsafeReadSideHandlerServiceServer(t testing.TB) *UnsafeReadSideHandlerServiceServer {
	mock := &UnsafeReadSideHandlerServiceServer{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
