// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeWriteSideHandlerServiceServer is an autogenerated mock type for the UnsafeWriteSideHandlerServiceServer type
type UnsafeWriteSideHandlerServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedWriteSideHandlerServiceServer provides a mock function with given fields:
func (_m *UnsafeWriteSideHandlerServiceServer) mustEmbedUnimplementedWriteSideHandlerServiceServer() {
	_m.Called()
}

type NewUnsafeWriteSideHandlerServiceServerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeWriteSideHandlerServiceServer creates a new instance of UnsafeWriteSideHandlerServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeWriteSideHandlerServiceServer(t NewUnsafeWriteSideHandlerServiceServerT) *UnsafeWriteSideHandlerServiceServer {
	mock := &UnsafeWriteSideHandlerServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
