/*
 * Copyright (c) The go-kit Authors
 */

package requestid

import (
	"context"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

var (
	unaryInfo = &grpc.UnaryServerInfo{
		FullMethod: "TestService.UnaryMethod",
	}
	streamInfo = &grpc.StreamServerInfo{
		FullMethod:     "TestService.StreamMethod",
		IsServerStream: true,
	}
)

// testServerStream is used for unit test.
// it implements the grpc.ServerStream interface
type testServerStream struct {
	grpc.ServerStream
	ctx context.Context
}

// Context returns the context for this stream.
func (s *testServerStream) Context() context.Context {
	return s.ctx
}

// SendMsg sends a message
func (s *testServerStream) SendMsg(_ interface{}) error {
	return nil
}

// RecvMsg blocks until it receives a message into m or the stream is done
func (s *testServerStream) RecvMsg(_ interface{}) error {
	return nil
}

func TestNewUnaryServerInterceptor(t *testing.T) {
	t.Run("with request ID set", func(t *testing.T) {
		// create a request ID
		requestID := uuid.NewString()
		// create a unary handler
		unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
			if got, want := FromContext(ctx), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}

			if got, want := FromContext(ctx), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}
			return "output", nil
		}

		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, requestID)
		ctx = metadata.NewIncomingContext(ctx, md)
		_, err := NewUnaryServerInterceptor()(ctx, "xyz", unaryInfo, unaryHandler)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})
	t.Run("with request ID is empty", func(t *testing.T) {
		// create a unary handler
		unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
			if got := FromContext(ctx); got == "" {
				t.Error("requestID must be generated by interceptor")
			}
			return "output", nil
		}

		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, "")
		ctx = metadata.NewIncomingContext(ctx, md)
		_, err := NewUnaryServerInterceptor()(ctx, "xyz", unaryInfo, unaryHandler)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})
	t.Run("without request ID", func(t *testing.T) {
		unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
			requestID := FromContext(ctx)
			if requestID == "" {
				t.Errorf("requestID must be generated by interceptor")
			}

			if got, want := FromContext(ctx), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}

			return "output", nil
		}

		ctx := context.Background()
		_, err := NewUnaryServerInterceptor()(ctx, "xyz", unaryInfo, unaryHandler)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})
}

func TestNewStreamServerInterceptor(t *testing.T) {
	t.Run("without request ID", func(t *testing.T) {
		streamHandler := func(srv interface{}, stream grpc.ServerStream) error {
			requestID := FromContext(stream.Context())
			if requestID == "" {
				t.Errorf("requestID must be generated by interceptor")
			}

			if got, want := FromContext(stream.Context()), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}
			return nil
		}
		testService := struct{}{}
		testStream := &testServerStream{ctx: context.Background()}
		err := NewStreamServerInterceptor()(testService, testStream, streamInfo, streamHandler)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})
	t.Run("with request ID", func(t *testing.T) {
		// create the request ID
		requestID := uuid.NewString()
		// create the stream handler
		streamHandler := func(srv interface{}, stream grpc.ServerStream) error {
			requestID := FromContext(stream.Context())
			if requestID == "" {
				t.Errorf("requestID must be generated by interceptor")
			}

			if got, want := FromContext(stream.Context()), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}
			return nil
		}
		testService := struct{}{}
		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, requestID)
		ctx = metadata.NewIncomingContext(ctx, md)
		testStream := &testServerStream{ctx: ctx}
		err := NewStreamServerInterceptor()(testService, testStream, streamInfo, streamHandler)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})
	t.Run("with request ID is empty", func(t *testing.T) {
		// create the stream handler
		streamHandler := func(srv interface{}, stream grpc.ServerStream) error {
			requestID := FromContext(stream.Context())
			if requestID == "" {
				t.Error("requestID must be generated by interceptor")
			}
			return nil
		}
		testService := struct{}{}
		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, "")
		ctx = metadata.NewIncomingContext(ctx, md)
		testStream := &testServerStream{ctx: ctx}
		err := NewStreamServerInterceptor()(testService, testStream, streamInfo, streamHandler)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})
}

func TestFromContextWithNoKeySet(t *testing.T) {
	if rid := FromContext(context.Background()); rid != "" {
		t.Fatalf("got non-empty id from empty context")
	}
}

func TestNewUnaryClientInterceptor(t *testing.T) {
	t.Run("with request ID set", func(t *testing.T) {
		// get an instance of the interceptor
		interceptor := NewUnaryClientInterceptor()
		// create a request ID
		requestID := uuid.NewString()
		// set the request ID
		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, requestID)
		ctx = metadata.NewOutgoingContext(ctx, md)
		// call the interceptor
		err := interceptor(ctx, "test", "req", "reply", nil, func(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, opts ...grpc.CallOption) error {
			if got, want := FromContext(ctx), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}
			return nil
		})
		require.NoError(t, err)
	})
	t.Run("with empty request ID", func(t *testing.T) {
		// get an instance of the interceptor
		interceptor := NewUnaryClientInterceptor()
		// set the request ID
		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, "")
		ctx = metadata.NewOutgoingContext(ctx, md)
		// call the interceptor
		err := interceptor(ctx, "test", "req", "reply", nil, func(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, opts ...grpc.CallOption) error {
			if got := FromContext(ctx); got == "" {
				t.Error("expect requestID to be set")
			}
			return nil
		})
		require.NoError(t, err)
	})
	t.Run("with request ID not set", func(t *testing.T) {
		// get an instance of the interceptor
		interceptor := NewUnaryClientInterceptor()
		// set the request ID
		ctx := context.Background()
		// call the interceptor
		err := interceptor(ctx, "test", "req", "reply", nil, func(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, opts ...grpc.CallOption) error {
			if got := FromContext(ctx); got == "" {
				t.Error("expect requestID to be set")
			}
			return nil
		})
		require.NoError(t, err)
	})
}

func TestNewStreamClientInterceptor(t *testing.T) {
	t.Run("with request ID set", func(t *testing.T) {
		// get an instance of the interceptor
		interceptor := NewStreamClientInterceptor()
		// create a request ID
		requestID := uuid.NewString()
		// set the request ID
		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, requestID)
		ctx = metadata.NewOutgoingContext(ctx, md)
		// call the interceptor
		_, err := interceptor(ctx, &grpc.StreamDesc{StreamName: "test"}, nil, "test", func(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, opts ...grpc.CallOption) (grpc.ClientStream, error) {
			if got, want := FromContext(ctx), requestID; got != want {
				t.Errorf("expect requestID to %q, but got %q", want, got)
			}
			return nil, nil
		})
		require.NoError(t, err)
	})
	t.Run("with empty request ID", func(t *testing.T) {
		// get an instance of the interceptor
		interceptor := NewStreamClientInterceptor()
		// set the request ID
		ctx := context.Background()
		md := metadata.Pairs(XRequestIDMetadataKey, "")
		ctx = metadata.NewOutgoingContext(ctx, md)
		// call the interceptor
		_, err := interceptor(ctx, &grpc.StreamDesc{StreamName: "test"}, nil, "test", func(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, opts ...grpc.CallOption) (grpc.ClientStream, error) {
			if got := FromContext(ctx); got == "" {
				t.Error("expect requestID to be set")
			}
			return nil, nil
		})
		require.NoError(t, err)
	})
}
